"""
OpenCV Drawing Overlay - Auto-generated by OpenCV HUD Editor
"""
import cv2
import numpy as np


class DrawingOverlay:
    """
    Клас для малювання overlay графіки на кадрі
    
    Система координат: як у редакторі (0,0 в лівому верхньому куті)
    
    Кількість фігур: 35
    """
    
    def __init__(self):
        """Ініціалізація кольорів та констант"""
        # Кольори (BGR формат)
        self.colors = {
            'green': (0, 255, 0),
        }
    
    def draw(self, frame):
        """
        Намалювати всі фігури на кадрі
        
        Args:
            frame: np.ndarray (H, W, 3) BGR
        
        Returns:
            frame: np.ndarray з намальованими фігурами
        """
        cv2.line(frame, (600, 280), (600, 320), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (600, 340), (600, 360), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (620, 320), (660, 320), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (600, 280), (600, 260), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (580, 320), (540, 320), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 380), (580, 380), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 400), (580, 400), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 420), (580, 420), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 440), (580, 440), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 460), (580, 460), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 480), (580, 480), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 500), (580, 500), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 520), (580, 520), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 540), (580, 540), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (560, 560), (580, 560), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 380), (620, 380), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 400), (620, 400), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 420), (620, 420), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 440), (620, 440), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 460), (620, 460), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 480), (620, 480), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 500), (620, 500), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 520), (620, 520), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 540), (620, 540), self.colors['green'], 2, cv2.LINE_AA)
        cv2.line(frame, (640, 560), (620, 560), self.colors['green'], 2, cv2.LINE_AA)
        cv2.circle(frame, (600, 380), 3, self.colors['green'], -1, cv2.LINE_AA)
        cv2.circle(frame, (600, 400), 3, self.colors['green'], -1, cv2.LINE_AA)
        cv2.circle(frame, (600, 420), 3, self.colors['green'], -1, cv2.LINE_AA)
        cv2.circle(frame, (600, 440), 3, self.colors['green'], -1, cv2.LINE_AA)
        cv2.circle(frame, (600, 460), 3, self.colors['green'], -1, cv2.LINE_AA)
        cv2.circle(frame, (600, 480), 3, self.colors['green'], -1, cv2.LINE_AA)
        cv2.circle(frame, (600, 500), 3, self.colors['green'], -1, cv2.LINE_AA)
        cv2.circle(frame, (600, 520), 3, self.colors['green'], -1, cv2.LINE_AA)
        cv2.circle(frame, (600, 540), 3, self.colors['green'], -1, cv2.LINE_AA)
        cv2.circle(frame, (600, 560), 3, self.colors['green'], -1, cv2.LINE_AA)
        
        return frame


# Приклад використання:
if __name__ == '__main__':
    # Створюємо overlay
    overlay = DrawingOverlay()
    
    # Читаємо або створюємо кадр
    frame = np.zeros((720, 1280, 3), dtype=np.uint8)  # Чорний кадр
    # або завантажте з відео/камери:
    cap = cv2.VideoCapture(0)
    ret, frame = cap.read()
    
    # Малюємо overlay
    frame = overlay.draw(frame)
    
    # Показуємо результат
    cv2.imshow('Overlay', frame)
    cv2.waitKey(0)
    cv2.destroyAllWindows()